platform :ios, '9.3'
inhibit_all_warnings!
use_frameworks!
#use_modular_headers!

flutter_application_path = '../../br-web-MeuespacoClienteMobile-flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

def default_pods
  #pod 'Google/CloudMessaging'
  pod 'FBAEMKit', '~> 11.0'
  pod 'FBSDKCoreKit', '~> 11.0'
  pod 'FBSDKLoginKit', '~> 11.0'
  pod 'FBSDKShareKit', '~> 11.0'
  pod 'Firebase', '~> 6.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'GoogleSignIn', '4.4.0'
  pod 'UITextView+Placeholder', '~> 1.2'
  pod "VMaskTextField"
  #pod 'Google/Analytics'
  pod "UIImage-ResizeMagick"
  pod "RMessage"
  pod 'FontAwesome'
  pod 'FontAwesome.swift'
  #pod 'MarketingCloudSDK'
end

target 'appsegurado' do
	default_pods
  install_all_flutter_pods(flutter_application_path)
end

target 'AppAliro' do
	default_pods
  install_all_flutter_pods(flutter_application_path)
end


